### ISSUE TITLE
Let effects declare they depend on global transform

### ISSUE THREAD

**Issue by tkarabela** [eliemichel/OpenMeshEffect#11]
Now that we have #5, I've tried it in the Blender implementation and noticed that while the transform is passed correctly, it only gets passed in once when the modifier is created. Changing the transform interactively does not lead to re-cooking.

This seems like good default behavior and optimization, but it makes the transform kinda pointless.

We should let the effect declare at describe time that it depends on the transform, so that the host can re-cook it as needed. Should it be "global" like the deformer property, or tied to input mesh (so that the effect can depend on transform of some input, but not other input - would that be even useful)?

**Comment by eliemichel** [comment]
Fixed with the introduction of `kOfxInputPropRequestTransform` in 3fb92c3

https://user-images.githubusercontent.com/5802849/103464468-2dfb1580-4d34-11eb-93fc-4ca4a5ca801f.mp4
